#!/bin/sh
#
# Usage: ~/docker/letsencrypt/add_domain yourdomain.com you@email.com
#
docker run -it --rm --name letsencrypt \
  -v "/var/lib/letsencrypt:/var/lib/letsencrypt" \
  --volumes-from nginx \
  certbot/certbot \
  certonly \
  --webroot \
  --webroot-path /var/www/html \
  --agree-tos \
  --renew-by-default \
  -d $1 \
  -m $2
